import { IssueAssetDefinition, IssueType } from './solarIssueTypes';

type IssueAssetLibrary = Record<IssueType, IssueAssetDefinition>;

export const ISSUE_ASSET_LIBRARY: IssueAssetLibrary = {
  hotspot: {
    videoUrl: 'https://videos.pexels.com/video-files/8092472/8092472-uhd_2560_1440_25fps.mp4',
    poster: {
      title: 'Hotspot Detected',
      subtitle: 'Cell overheating pattern',
      accentFrom: '#ef4444',
      accentTo: '#f97316',
    },
    description: 'Thermal anomaly detected - immediate inspection required',
    typicalSeverity: 'critical',
    energyLossRange: [15, 35],
    visualEffect: 'Thermal glow pulsing on panel cells',
    recommendations: [
      'Schedule immediate thermal inspection',
      'Check for cell bypass diode failure',
      'Verify string voltage and current',
      'Consider panel replacement if severe',
    ],
    accent: { from: '#f97316', to: '#facc15' },
    historyTimeline: [
      { label: '24h ago', hoursAgo: 24, notes: 'Initial mild heating visible', severity: 'high' },
      { label: '12h ago', hoursAgo: 12, notes: 'Hotspot expanding across cells', severity: 'high' },
      { label: '1h ago', hoursAgo: 1, notes: 'Critical temperature spike detected', severity: 'critical' },
    ],
  },
  crack: {
    videoUrl: 'https://videos.pexels.com/video-files/9604094/9604094-uhd_2560_1440_24fps.mp4',
    poster: {
      title: 'Cracked Glass',
      subtitle: 'Micro-fracture on string',
      accentFrom: '#7c3aed',
      accentTo: '#ec4899',
    },
    description: 'Physical crack detected on panel surface',
    typicalSeverity: 'high',
    energyLossRange: [10, 25],
    visualEffect: 'Micro-crack appearing with reflection',
    recommendations: [
      'Document crack size and location',
      'Monitor for crack expansion',
      'Check warranty coverage',
      'Plan panel replacement',
    ],
    accent: { from: '#7c3aed', to: '#ec4899' },
    historyTimeline: [
      { label: '3d ago', hoursAgo: 72, notes: 'Hairline fracture detected', severity: 'medium' },
      { label: '24h ago', hoursAgo: 24, notes: 'Crack spreading across cells', severity: 'high' },
      { label: 'Now', hoursAgo: 0.5, notes: 'Structural integrity compromised', severity: 'high' },
    ],
  },
  soiling: {
    videoUrl: 'https://videos.pexels.com/video-files/6076970/6076970-uhd_3840_2160_25fps.mp4',
    poster: {
      title: 'Bird Droppings',
      subtitle: 'Soiling across cells',
      accentFrom: '#ca8a04',
      accentTo: '#facc15',
    },
    description: 'Heavy dust accumulation reducing efficiency',
    typicalSeverity: 'medium',
    energyLossRange: [5, 15],
    visualEffect: 'Dust layer reducing shine',
    recommendations: [
      'Schedule cleaning service',
      'Consider automated cleaning system',
      'Check local weather patterns',
      'Implement preventive maintenance',
    ],
    accent: { from: '#b45309', to: '#f59e0b' },
    historyTimeline: [
      { label: '7d ago', hoursAgo: 168, notes: 'Light debris detected on upper cells', severity: 'low' },
      { label: '2d ago', hoursAgo: 48, notes: 'Bird droppings covering cell junction', severity: 'medium' },
      { label: 'Today', hoursAgo: 2, notes: 'Generation loss exceeds 12%', severity: 'medium' },
    ],
  },
  delamination: {
    videoUrl: 'https://videos.pexels.com/video-files/4496260/4496260-uhd_3840_2160_24fps.mp4',
    poster: {
      title: 'Delamination',
      subtitle: 'Encapsulant bubbling',
      accentFrom: '#0ea5e9',
      accentTo: '#22d3ee',
    },
    description: 'Layer separation detected - monitor closely',
    typicalSeverity: 'high',
    energyLossRange: [12, 30],
    visualEffect: 'Film bubble growth',
    recommendations: [
      'Inspect for water ingress',
      'Check warranty status',
      'Monitor progression rate',
      'Plan panel replacement',
    ],
    accent: { from: '#0ea5e9', to: '#22d3ee' },
    historyTimeline: [
      { label: '10d ago', hoursAgo: 240, notes: 'Minor delamination around edges', severity: 'medium' },
      { label: '3d ago', hoursAgo: 72, notes: 'Encapsulant bubbling expanding', severity: 'high' },
      { label: 'Now', hoursAgo: 1, notes: 'Moisture ingress imminent', severity: 'high' },
    ],
  },
  shadow: {
    videoUrl: 'https://videos.pexels.com/video-files/6077448/6077448-uhd_3840_2160_25fps.mp4',
    poster: {
      title: 'Cloud Shading',
      subtitle: 'Passing cumulus cover',
      accentFrom: '#1d4ed8',
      accentTo: '#0ea5e9',
    },
    description: 'Shading detected affecting output',
    typicalSeverity: 'medium',
    energyLossRange: [20, 50],
    visualEffect: 'Dynamic shade from nearby object',
    recommendations: [
      'Identify shading source',
      'Trim vegetation if applicable',
      'Consider panel relocation',
      'Install bypass diodes',
    ],
    accent: { from: '#1d4ed8', to: '#0ea5e9' },
    historyTimeline: [
      { label: '2d ago', hoursAgo: 48, notes: 'Morning shading from tree growth', severity: 'medium' },
      { label: '12h ago', hoursAgo: 12, notes: 'Cloud bank causes intermittent losses', severity: 'medium' },
      { label: 'Now', hoursAgo: 0.5, notes: 'Heavy shading reducing string output', severity: 'medium' },
    ],
  },
  snow: {
    videoUrl: 'https://videos.pexels.com/video-files/2675514/2675514-uhd_2560_1440_25fps.mp4',
    poster: {
      title: 'Snow Cover',
      subtitle: 'Panels partially buried',
      accentFrom: '#94a3b8',
      accentTo: '#38bdf8',
    },
    description: 'Snow coverage affecting generation',
    typicalSeverity: 'low',
    energyLossRange: [80, 100],
    visualEffect: 'Snow layer on panel surface',
    recommendations: [
      'Monitor for natural snow melt',
      'Consider snow removal if urgent',
      'Check tilt angle optimization',
      'Install heating elements for frequent snow',
    ],
    accent: { from: '#94a3b8', to: '#38bdf8' },
    historyTimeline: [
      { label: '18h ago', hoursAgo: 18, notes: 'Light dusting accumulating', severity: 'low' },
      { label: '6h ago', hoursAgo: 6, notes: 'Partial snow cover on lower string', severity: 'medium' },
      { label: 'Now', hoursAgo: 0.5, notes: 'Thick snow layer blocking output', severity: 'medium' },
    ],
  },
  none: {
    videoUrl: 'https://videos.pexels.com/video-files/2611250/2611250-uhd_2560_1440_30fps.mp4',
    poster: {
      title: 'All Clear',
      subtitle: 'No issues detected',
      accentFrom: '#4ade80',
      accentTo: '#22c55e',
    },
    description: 'All panels operating within normal parameters',
    typicalSeverity: 'info',
    energyLossRange: [0, 2],
    visualEffect: 'Normal operation',
    recommendations: [
      'Continue monitoring',
      'Maintain regular cleaning schedule',
      'Keep up preventive maintenance',
      'Review performance quarterly',
    ],
    accent: { from: '#22c55e', to: '#4ade80' },
    historyTimeline: [
      { label: '7d ago', hoursAgo: 168, notes: 'All strings nominal', severity: 'info' },
      { label: '24h ago', hoursAgo: 24, notes: 'Healthy production trend', severity: 'info' },
      { label: 'Now', hoursAgo: 0.5, notes: 'No alerts detected', severity: 'info' },
    ],
  },
};
